<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProvinciaSeeder extends Seeder
{
    public function run(): void
    {
        $provincias = [
            ['id_provincia' => 1, 'nombre' => 'BAGUA', 'id_departamento' => 1],
            ['id_provincia' => 2, 'nombre' => 'BONGARA', 'id_departamento' => 1],
            ['id_provincia' => 3, 'nombre' => 'CHACHAPOYAS', 'id_departamento' => 1],
            ['id_provincia' => 4, 'nombre' => 'CONDORCANQUI', 'id_departamento' => 1],
            ['id_provincia' => 5, 'nombre' => 'LUYA', 'id_departamento' => 1],
            ['id_provincia' => 6, 'nombre' => 'RODRIGUEZ DE MENDOZA', 'id_departamento' => 1],
            ['id_provincia' => 7, 'nombre' => 'UTCUBAMBA', 'id_departamento' => 1],
            ['id_provincia' => 8, 'nombre' => 'AIJA', 'id_departamento' => 2],
            ['id_provincia' => 9, 'nombre' => 'ANTONIO RAYMONDI', 'id_departamento' => 2],
            ['id_provincia' => 10, 'nombre' => 'ASUNCION', 'id_departamento' => 2],
            ['id_provincia' => 11, 'nombre' => 'BOLOGNESI', 'id_departamento' => 2],
            ['id_provincia' => 12, 'nombre' => 'CARHUAZ', 'id_departamento' => 2],
            ['id_provincia' => 13, 'nombre' => 'CARLOS FERMIN FITZCARRALD', 'id_departamento' => 2],
            ['id_provincia' => 14, 'nombre' => 'CASMA', 'id_departamento' => 2],
            ['id_provincia' => 15, 'nombre' => 'CORONGO', 'id_departamento' => 2],
            ['id_provincia' => 16, 'nombre' => 'HUARAZ', 'id_departamento' => 2],
            ['id_provincia' => 17, 'nombre' => 'HUARI', 'id_departamento' => 2],
            ['id_provincia' => 18, 'nombre' => 'HUARMEY', 'id_departamento' => 2],
            ['id_provincia' => 19, 'nombre' => 'HUAYLAS', 'id_departamento' => 2],
            ['id_provincia' => 20, 'nombre' => 'MARISCAL LUZURIAGA', 'id_departamento' => 2],
            ['id_provincia' => 21, 'nombre' => 'OCROS', 'id_departamento' => 2],
            ['id_provincia' => 22, 'nombre' => 'PALLASCA', 'id_departamento' => 2],
            ['id_provincia' => 23, 'nombre' => 'POMABAMBA', 'id_departamento' => 2],
            ['id_provincia' => 24, 'nombre' => 'RECUAY', 'id_departamento' => 2],
            ['id_provincia' => 25, 'nombre' => 'SANTA', 'id_departamento' => 2],
            ['id_provincia' => 26, 'nombre' => 'SIHUAS', 'id_departamento' => 2],
            ['id_provincia' => 27, 'nombre' => 'YUNGAY', 'id_departamento' => 2],
            ['id_provincia' => 28, 'nombre' => 'ABANCAY', 'id_departamento' => 3],
            ['id_provincia' => 29, 'nombre' => 'ANDAHUAYLAS', 'id_departamento' => 3],
            ['id_provincia' => 30, 'nombre' => 'ANTABAMBA', 'id_departamento' => 3],
            ['id_provincia' => 31, 'nombre' => 'AYMARAES', 'id_departamento' => 3],
            ['id_provincia' => 32, 'nombre' => 'CHINCHEROS', 'id_departamento' => 3],
            ['id_provincia' => 33, 'nombre' => 'COTABAMBAS', 'id_departamento' => 3],
            ['id_provincia' => 34, 'nombre' => 'GRAU', 'id_departamento' => 3],
            ['id_provincia' => 35, 'nombre' => 'AREQUIPA', 'id_departamento' => 4],
            ['id_provincia' => 36, 'nombre' => 'CAMANA', 'id_departamento' => 4],
            ['id_provincia' => 37, 'nombre' => 'CARAVELI', 'id_departamento' => 4],
            ['id_provincia' => 38, 'nombre' => 'CASTILLA', 'id_departamento' => 4],
            ['id_provincia' => 39, 'nombre' => 'CAYLLOMA', 'id_departamento' => 4],
            ['id_provincia' => 40, 'nombre' => 'CONDESUYOS', 'id_departamento' => 4],
            ['id_provincia' => 41, 'nombre' => 'ISLAY', 'id_departamento' => 4],
            ['id_provincia' => 42, 'nombre' => 'LA UNION', 'id_departamento' => 4],
            ['id_provincia' => 43, 'nombre' => 'CANGALLO', 'id_departamento' => 5],
            ['id_provincia' => 44, 'nombre' => 'HUAMANGA', 'id_departamento' => 5],
            ['id_provincia' => 45, 'nombre' => 'HUANCA SANCOS', 'id_departamento' => 5],
            ['id_provincia' => 46, 'nombre' => 'HUANTA', 'id_departamento' => 5],
            ['id_provincia' => 47, 'nombre' => 'LA MAR', 'id_departamento' => 5],
            ['id_provincia' => 48, 'nombre' => 'LUCANAS', 'id_departamento' => 5],
            ['id_provincia' => 49, 'nombre' => 'PARINACOCHAS', 'id_departamento' => 5],
            ['id_provincia' => 50, 'nombre' => 'PAUCAR DEL SARA SARA', 'id_departamento' => 5],
            ['id_provincia' => 51, 'nombre' => 'SUCRE', 'id_departamento' => 5],
            ['id_provincia' => 52, 'nombre' => 'VICTOR FAJARDO', 'id_departamento' => 5],
            ['id_provincia' => 53, 'nombre' => 'VILCAS HUAMAN', 'id_departamento' => 5],
            ['id_provincia' => 54, 'nombre' => 'CAJABAMBA', 'id_departamento' => 6],
            ['id_provincia' => 55, 'nombre' => 'CAJAMARCA', 'id_departamento' => 6],
            ['id_provincia' => 56, 'nombre' => 'CELENDIN', 'id_departamento' => 6],
            ['id_provincia' => 57, 'nombre' => 'CHOTA', 'id_departamento' => 6],
            ['id_provincia' => 58, 'nombre' => 'CONTUMAZA', 'id_departamento' => 6],
            ['id_provincia' => 59, 'nombre' => 'CUTERVO', 'id_departamento' => 6],
            ['id_provincia' => 60, 'nombre' => 'HUALGAYOC', 'id_departamento' => 6],
            ['id_provincia' => 61, 'nombre' => 'JAEN', 'id_departamento' => 6],
            ['id_provincia' => 62, 'nombre' => 'SAN IGNACIO', 'id_departamento' => 6],
            ['id_provincia' => 63, 'nombre' => 'SAN MARCOS', 'id_departamento' => 6],
            ['id_provincia' => 64, 'nombre' => 'SAN MIGUEL', 'id_departamento' => 6],
            ['id_provincia' => 65, 'nombre' => 'SAN PABLO', 'id_departamento' => 6],
            ['id_provincia' => 66, 'nombre' => 'SANTA CRUZ', 'id_departamento' => 6],
            ['id_provincia' => 67, 'nombre' => 'CALLAO', 'id_departamento' => 7],
            ['id_provincia' => 68, 'nombre' => 'ACOMAYO', 'id_departamento' => 8],
            ['id_provincia' => 69, 'nombre' => 'ANTA', 'id_departamento' => 8],
            ['id_provincia' => 70, 'nombre' => 'CALCA', 'id_departamento' => 8],
            ['id_provincia' => 71, 'nombre' => 'CANAS', 'id_departamento' => 8],
            ['id_provincia' => 72, 'nombre' => 'CANCHIS', 'id_departamento' => 8],
            ['id_provincia' => 73, 'nombre' => 'CHUMBIVILCAS', 'id_departamento' => 8],
            ['id_provincia' => 74, 'nombre' => 'CUSCO', 'id_departamento' => 8],
            ['id_provincia' => 75, 'nombre' => 'ESPINAR', 'id_departamento' => 8],
            ['id_provincia' => 76, 'nombre' => 'LA CONVENCION', 'id_departamento' => 8],
            ['id_provincia' => 77, 'nombre' => 'PARURO', 'id_departamento' => 8],
            ['id_provincia' => 78, 'nombre' => 'PAUCARTAMBO', 'id_departamento' => 8],
            ['id_provincia' => 79, 'nombre' => 'QUISPICANCHI', 'id_departamento' => 8],
            ['id_provincia' => 80, 'nombre' => 'URUBAMBA', 'id_departamento' => 8],
            ['id_provincia' => 81, 'nombre' => 'ACOBAMBA', 'id_departamento' => 9],
            ['id_provincia' => 82, 'nombre' => 'ANGARAES', 'id_departamento' => 9],
            ['id_provincia' => 83, 'nombre' => 'CASTROVIRREYNA', 'id_departamento' => 9],
            ['id_provincia' => 84, 'nombre' => 'CHURCAMPA', 'id_departamento' => 9],
            ['id_provincia' => 85, 'nombre' => 'HUANCAVELICA', 'id_departamento' => 9],
            ['id_provincia' => 86, 'nombre' => 'HUAYTARA', 'id_departamento' => 9],
            ['id_provincia' => 87, 'nombre' => 'TAYACAJA', 'id_departamento' => 9],
            ['id_provincia' => 88, 'nombre' => 'AMBO', 'id_departamento' => 10],
            ['id_provincia' => 89, 'nombre' => 'DOS DE MAYO', 'id_departamento' => 10],
            ['id_provincia' => 90, 'nombre' => 'HUACAYBAMBA', 'id_departamento' => 10],
            ['id_provincia' => 91, 'nombre' => 'HUAMALIES', 'id_departamento' => 10],
            ['id_provincia' => 92, 'nombre' => 'HUANUCO', 'id_departamento' => 10],
            ['id_provincia' => 93, 'nombre' => 'LAURICOCHA', 'id_departamento' => 10],
            ['id_provincia' => 94, 'nombre' => 'LEONCIO PRADO', 'id_departamento' => 10],
            ['id_provincia' => 95, 'nombre' => 'MARAÑON', 'id_departamento' => 10],
            ['id_provincia' => 96, 'nombre' => 'PACHITEA', 'id_departamento' => 10],
            ['id_provincia' => 97, 'nombre' => 'PUERTO INCA', 'id_departamento' => 10],
            ['id_provincia' => 98, 'nombre' => 'YAROWILCA', 'id_departamento' => 10],
            ['id_provincia' => 99, 'nombre' => 'CHINCHA', 'id_departamento' => 11],
            ['id_provincia' => 100, 'nombre' => 'ICA', 'id_departamento' => 11],
            ['id_provincia' => 101, 'nombre' => 'NAZCA', 'id_departamento' => 11],
            ['id_provincia' => 102, 'nombre' => 'PALPA', 'id_departamento' => 11],
            ['id_provincia' => 103, 'nombre' => 'PISCO', 'id_departamento' => 11],
            ['id_provincia' => 104, 'nombre' => 'CHANCHAMAYO', 'id_departamento' => 12],
            ['id_provincia' => 105, 'nombre' => 'CHUPACA', 'id_departamento' => 12],
            ['id_provincia' => 106, 'nombre' => 'CONCEPCION', 'id_departamento' => 12],
            ['id_provincia' => 107, 'nombre' => 'HUANCAYO', 'id_departamento' => 12],
            ['id_provincia' => 108, 'nombre' => 'JAUJA', 'id_departamento' => 12],
            ['id_provincia' => 109, 'nombre' => 'JUNIN', 'id_departamento' => 12],
            ['id_provincia' => 110, 'nombre' => 'SATIPO', 'id_departamento' => 12],
            ['id_provincia' => 111, 'nombre' => 'TARMA', 'id_departamento' => 12],
            ['id_provincia' => 112, 'nombre' => 'YAULI', 'id_departamento' => 12],
            ['id_provincia' => 113, 'nombre' => 'ASCOPE', 'id_departamento' => 13],
            ['id_provincia' => 114, 'nombre' => 'BOLIVAR', 'id_departamento' => 13],
            ['id_provincia' => 115, 'nombre' => 'CHEPEN', 'id_departamento' => 13],
            ['id_provincia' => 116, 'nombre' => 'GRAN CHIMU', 'id_departamento' => 13],
            ['id_provincia' => 117, 'nombre' => 'JULCAN', 'id_departamento' => 13],
            ['id_provincia' => 118, 'nombre' => 'OTUZCO', 'id_departamento' => 13],
            ['id_provincia' => 119, 'nombre' => 'PACASMAYO', 'id_departamento' => 13],
            ['id_provincia' => 120, 'nombre' => 'PATAZ', 'id_departamento' => 13],
            ['id_provincia' => 121, 'nombre' => 'SANCHEZ CARRION', 'id_departamento' => 13],
            ['id_provincia' => 122, 'nombre' => 'SANTIAGO DE CHUCO', 'id_departamento' => 13],
            ['id_provincia' => 123, 'nombre' => 'TRUJILLO', 'id_departamento' => 13],
            ['id_provincia' => 124, 'nombre' => 'VIRU', 'id_departamento' => 13],
            ['id_provincia' => 125, 'nombre' => 'CHICLAYO', 'id_departamento' => 14],
            ['id_provincia' => 126, 'nombre' => 'FERREÑAFE', 'id_departamento' => 14],
            ['id_provincia' => 127, 'nombre' => 'LAMBAYEQUE', 'id_departamento' => 14],
            ['id_provincia' => 128, 'nombre' => 'BARRANCA', 'id_departamento' => 15],
            ['id_provincia' => 129, 'nombre' => 'CAJATAMBO', 'id_departamento' => 15],
            ['id_provincia' => 130, 'nombre' => 'CANTA', 'id_departamento' => 15],
            ['id_provincia' => 131, 'nombre' => 'CAÑETE', 'id_departamento' => 15],
            ['id_provincia' => 132, 'nombre' => 'HUARAL', 'id_departamento' => 15],
            ['id_provincia' => 133, 'nombre' => 'HUAROCHIRI', 'id_departamento' => 15],
            ['id_provincia' => 134, 'nombre' => 'HUAURA', 'id_departamento' => 15],
            ['id_provincia' => 135, 'nombre' => 'LIMA', 'id_departamento' => 15],
            ['id_provincia' => 136, 'nombre' => 'OYON', 'id_departamento' => 15],
            ['id_provincia' => 137, 'nombre' => 'YAUYOS', 'id_departamento' => 15],
            ['id_provincia' => 138, 'nombre' => 'ALTO AMAZONAS', 'id_departamento' => 16],
            ['id_provincia' => 139, 'nombre' => 'DATEM DEL MARAÑON', 'id_departamento' => 16],
            ['id_provincia' => 140, 'nombre' => 'LORETO', 'id_departamento' => 16],
            ['id_provincia' => 141, 'nombre' => 'MARISCAL RAMON CASTILLA', 'id_departamento' => 16],
            ['id_provincia' => 142, 'nombre' => 'MAYNAS', 'id_departamento' => 16],
            ['id_provincia' => 143, 'nombre' => 'PUTUMAYO', 'id_departamento' => 16],
            ['id_provincia' => 144, 'nombre' => 'REQUENA', 'id_departamento' => 16],
            ['id_provincia' => 145, 'nombre' => 'UCAYALI', 'id_departamento' => 16],
            ['id_provincia' => 146, 'nombre' => 'MANU', 'id_departamento' => 17],
            ['id_provincia' => 147, 'nombre' => 'TAHUAMANU', 'id_departamento' => 17],
            ['id_provincia' => 148, 'nombre' => 'TAMBOPATA', 'id_departamento' => 17],
            ['id_provincia' => 149, 'nombre' => 'GENERAL SANCHEZ CERRO', 'id_departamento' => 18],
            ['id_provincia' => 150, 'nombre' => 'ILO', 'id_departamento' => 18],
            ['id_provincia' => 151, 'nombre' => 'MARISCAL NIETO', 'id_departamento' => 18],
            ['id_provincia' => 152, 'nombre' => 'DANIEL ALCIDES CARRION', 'id_departamento' => 19],
            ['id_provincia' => 153, 'nombre' => 'OXAPAMPA', 'id_departamento' => 19],
            ['id_provincia' => 154, 'nombre' => 'PASCO', 'id_departamento' => 19],
            ['id_provincia' => 155, 'nombre' => 'AYABACA', 'id_departamento' => 20],
            ['id_provincia' => 156, 'nombre' => 'HUANCABAMBA', 'id_departamento' => 20],
            ['id_provincia' => 157, 'nombre' => 'MORROPON', 'id_departamento' => 20],
            ['id_provincia' => 158, 'nombre' => 'PAITA', 'id_departamento' => 20],
            ['id_provincia' => 159, 'nombre' => 'PIURA', 'id_departamento' => 20],
            ['id_provincia' => 160, 'nombre' => 'SECHURA', 'id_departamento' => 20],
            ['id_provincia' => 161, 'nombre' => 'SULLANA', 'id_departamento' => 20],
            ['id_provincia' => 162, 'nombre' => 'TALARA', 'id_departamento' => 20],
            ['id_provincia' => 163, 'nombre' => 'AZANGARO', 'id_departamento' => 21],
            ['id_provincia' => 164, 'nombre' => 'CARABAYA', 'id_departamento' => 21],
            ['id_provincia' => 165, 'nombre' => 'CHUCUITO', 'id_departamento' => 21],
            ['id_provincia' => 166, 'nombre' => 'EL COLLAO', 'id_departamento' => 21],
            ['id_provincia' => 167, 'nombre' => 'HUANCANE', 'id_departamento' => 21],
            ['id_provincia' => 168, 'nombre' => 'LAMPA', 'id_departamento' => 21],
            ['id_provincia' => 169, 'nombre' => 'MELGAR', 'id_departamento' => 21],
            ['id_provincia' => 170, 'nombre' => 'MOHO', 'id_departamento' => 21],
            ['id_provincia' => 171, 'nombre' => 'PUNO', 'id_departamento' => 21],
            ['id_provincia' => 172, 'nombre' => 'SAN ANTONIO DE PUTINA', 'id_departamento' => 21],
            ['id_provincia' => 173, 'nombre' => 'SAN ROMAN', 'id_departamento' => 21],
            ['id_provincia' => 174, 'nombre' => 'SANDIA', 'id_departamento' => 21],
            ['id_provincia' => 175, 'nombre' => 'YUNGUYO', 'id_departamento' => 21],
            ['id_provincia' => 176, 'nombre' => 'BELLAVISTA', 'id_departamento' => 22],
            ['id_provincia' => 177, 'nombre' => 'EL DORADO', 'id_departamento' => 22],
            ['id_provincia' => 178, 'nombre' => 'HUALLAGA', 'id_departamento' => 22],
            ['id_provincia' => 179, 'nombre' => 'LAMAS', 'id_departamento' => 22],
            ['id_provincia' => 180, 'nombre' => 'MARISCAL CACERES', 'id_departamento' => 22],
            ['id_provincia' => 181, 'nombre' => 'MOYOBAMBA', 'id_departamento' => 22],
            ['id_provincia' => 182, 'nombre' => 'PICOTA', 'id_departamento' => 22],
            ['id_provincia' => 183, 'nombre' => 'RIOJA', 'id_departamento' => 22],
            ['id_provincia' => 184, 'nombre' => 'SAN MARTIN', 'id_departamento' => 22],
            ['id_provincia' => 185, 'nombre' => 'TOCACHE', 'id_departamento' => 22],
            ['id_provincia' => 186, 'nombre' => 'CANDARAVE', 'id_departamento' => 23],
            ['id_provincia' => 187, 'nombre' => 'JORGE BASADRE', 'id_departamento' => 23],
            ['id_provincia' => 188, 'nombre' => 'TACNA', 'id_departamento' => 23],
            ['id_provincia' => 189, 'nombre' => 'TARATA', 'id_departamento' => 23],
            ['id_provincia' => 190, 'nombre' => 'CONTRALMIRANTE VILLAR', 'id_departamento' => 24],
            ['id_provincia' => 191, 'nombre' => 'TUMBES', 'id_departamento' => 24],
            ['id_provincia' => 192, 'nombre' => 'ZARUMILLA', 'id_departamento' => 24],
            ['id_provincia' => 193, 'nombre' => 'ATALAYA', 'id_departamento' => 25],
            ['id_provincia' => 194, 'nombre' => 'CORONEL PORTILLO', 'id_departamento' => 25],
            ['id_provincia' => 195, 'nombre' => 'PADRE ABAD', 'id_departamento' => 25],
            ['id_provincia' => 196, 'nombre' => 'PURUS', 'id_departamento' => 25],
        ];

        foreach ($provincias as $provincia) {
            DB::table('provincia')->updateOrInsert(
                ['id_provincia' => $provincia['id_provincia']],
                $provincia
            );
        }
    }
}
